sonar.projectKey=DermaNube
sonar.projectName=DermaNube
sonar.sources=Aplicacion
sonar.tests=Aplicacion
sonar.test.inclusions=**/Pruebas/**
sonar.exclusions=**/node_modules/**,**/public/recursos/**
sonar.javascript.lcov.reportPaths=Cobertura/lcov.info
sonar.sourceEncoding=UTF-8
