export const especialistasIniciales = [
  {
    id: "ESP001",
    tipo: "Especialista",
    correo: "valeria.rios@dermanube.local",
    nombre: "Valeria Ríos",
    especialidad: "Dermatología clínica",
    experiencia: 12,
    calificacion: 4.9,
    opiniones: 184,
    sede: "Trujillo Centro",
    precio: 130,
    modalidades: ["Presencial", "En línea"],
    resumen: "Atención integral de acné, dermatitis y salud preventiva de la piel.",
    disponible: true
  },
  {
    id: "ESP002",
    tipo: "Especialista",
    correo: "mateo.salazar@dermanube.local",
    nombre: "Mateo Salazar",
    especialidad: "Dermatología capilar",
    experiencia: 9,
    calificacion: 4.8,
    opiniones: 121,
    sede: "California",
    precio: 145,
    modalidades: ["Presencial"],
    resumen: "Diagnóstico y seguimiento personalizado de alopecia y alteraciones del cuero cabelludo.",
    disponible: true
  },
  {
    id: "ESP003",
    tipo: "Especialista",
    correo: "lucia.cardenas@dermanube.local",
    nombre: "Lucía Cárdenas",
    especialidad: "Dermatología estética",
    experiencia: 14,
    calificacion: 4.9,
    opiniones: 207,
    sede: "El Golf",
    precio: 160,
    modalidades: ["Presencial", "En línea"],
    resumen: "Tratamientos dermatológicos con enfoque conservador y seguimiento fotográfico.",
    disponible: true
  },
  {
    id: "ESP004",
    tipo: "Especialista",
    correo: "andres.vega@dermanube.local",
    nombre: "Andrés Vega",
    especialidad: "Oncología dermatológica",
    experiencia: 16,
    calificacion: 4.9,
    opiniones: 96,
    sede: "Primavera",
    precio: 180,
    modalidades: ["Presencial"],
    resumen: "Evaluación de lunares, prevención y diagnóstico temprano de lesiones cutáneas.",
    disponible: true
  },
  {
    id: "ESP005",
    tipo: "Especialista",
    correo: "camila.mendoza@dermanube.local",
    nombre: "Camila Mendoza",
    especialidad: "Dermatología pediátrica",
    experiencia: 10,
    calificacion: 4.8,
    opiniones: 88,
    sede: "San Andrés",
    precio: 140,
    modalidades: ["Presencial", "En línea"],
    resumen: "Atención dermatológica de niños y adolescentes con orientación para la familia.",
    disponible: true
  }
]
