apiVersion: 1

contactPoints:
  - orgId: 1
    name: WebhookServicioCitas
    receivers:
      - uid: webhookServicioCitas
        type: webhook
        settings:
          url: http://serviciocitas:3002/citas/alertas
          httpMethod: POST

policies:
  - orgId: 1
    receiver: WebhookServicioCitas
    group_by: [grafana_folder, alertname]
    group_wait: 10s
    group_interval: 1m
    repeat_interval: 4h
